import { prisma } from "../src/lib/prisma";

const categories = [
	// System categories - common expense categories
	{
		name: "Food & Dining",
		icon: "🍔",
		color: "#FF6B6B",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Transportation",
		icon: "🚗",
		color: "#4ECDC4",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Shopping",
		icon: "🛍️",
		color: "#95E1D3",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Entertainment",
		icon: "🎬",
		color: "#F38181",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Bills & Utilities",
		icon: "💡",
		color: "#AA96DA",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Healthcare",
		icon: "⚕️",
		color: "#FCBAD3",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Education",
		icon: "📚",
		color: "#A8D8EA",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Travel",
		icon: "✈️",
		color: "#FFD93D",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Salary",
		icon: "💰",
		color: "#6BCB77",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Investments",
		icon: "📈",
		color: "#4D96FF",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Gifts",
		icon: "🎁",
		color: "#FF85A2",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Subscriptions",
		icon: "📱",
		color: "#9381FF",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Personal Care",
		icon: "💅",
		color: "#FFB4B4",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Rent",
		icon: "🏠",
		color: "#F8AD9D",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Insurance",
		icon: "🛡️",
		color: "#74B9FF",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Data & Airtime",
		icon: "📱",
		color: "#4A90E2",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Betting & Gaming",
		icon: "🎲",
		color: "#E24A4A",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Generator & Fuel",
		icon: "⚡",
		color: "#FFB900",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Groceries",
		icon: "🛒",
		color: "#52C41A",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Restaurants & Takeout",
		icon: "🍕",
		color: "#FA8C16",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Parking & Tolls",
		icon: "🅿️",
		color: "#1890FF",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Taxi & Ride Sharing",
		icon: "🚕",
		color: "#13C2C2",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Clothing & Accessories",
		icon: "👕",
		color: "#EB2F96",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Electronics",
		icon: "💻",
		color: "#722ED1",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Home & Garden",
		icon: "🏡",
		color: "#87D068",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Sports & Fitness",
		icon: "⚽",
		color: "#2F54EB",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Movies & Cinema",
		icon: "🎥",
		color: "#F5222D",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Music & Concerts",
		icon: "🎵",
		color: "#FA541C",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Books & Magazines",
		icon: "📖",
		color: "#8C8C8C",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Electricity",
		icon: "💡",
		color: "#FADB14",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Water",
		icon: "💧",
		color: "#1890FF",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Internet & Cable",
		icon: "📡",
		color: "#531DAB",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Doctor & Hospital",
		icon: "🏥",
		color: "#FF4D4F",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Pharmacy & Medicine",
		icon: "💊",
		color: "#13C2C2",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Dental Care",
		icon: "🦷",
		color: "#52C41A",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Tuition & Fees",
		icon: "🎓",
		color: "#1890FF",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "School Supplies",
		icon: "✏️",
		color: "#FA8C16",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Online Courses",
		icon: "💻",
		color: "#722ED1",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Hotels & Accommodation",
		icon: "🏨",
		color: "#EB2F96",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Flight Tickets",
		icon: "🛫",
		color: "#1890FF",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Visa & Passport",
		icon: "🛂",
		color: "#722ED1",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Business Income",
		icon: "💼",
		color: "#52C41A",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Freelance Income",
		icon: "💻",
		color: "#13C2C2",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Interest & Dividends",
		icon: "📊",
		color: "#1890FF",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Rental Income",
		icon: "🏠",
		color: "#FA8C16",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Stocks & Bonds",
		icon: "📈",
		color: "#2F54EB",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Cryptocurrency",
		icon: "₿",
		color: "#FA8C16",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Savings & Deposits",
		icon: "🏦",
		color: "#52C41A",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Birthday Gifts",
		icon: "🎂",
		color: "#EB2F96",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Wedding Gifts",
		icon: "💒",
		color: "#FA541C",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Charity & Donations",
		icon: "❤️",
		color: "#F5222D",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Streaming Services",
		icon: "📺",
		color: "#722ED1",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Software & Apps",
		icon: "📱",
		color: "#1890FF",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Gym Membership",
		icon: "💪",
		color: "#FA541C",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Haircut & Salon",
		icon: "💇",
		color: "#EB2F96",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Spa & Massage",
		icon: "💆",
		color: "#13C2C2",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Laundry & Cleaning",
		icon: "🧺",
		color: "#52C41A",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Mortgage",
		icon: "🏡",
		color: "#8C8C8C",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Property Tax",
		icon: "🏘️",
		color: "#FA8C16",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Home Maintenance",
		icon: "🔧",
		color: "#1890FF",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Life Insurance",
		icon: "🛡️",
		color: "#2F54EB",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Health Insurance",
		icon: "⚕️",
		color: "#13C2C2",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Car Insurance",
		icon: "🚗",
		color: "#FA541C",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Pet Care",
		icon: "🐕",
		color: "#FA8C16",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Childcare & Daycare",
		icon: "👶",
		color: "#EB2F96",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Taxes",
		icon: "📋",
		color: "#8C8C8C",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Legal Fees",
		icon: "⚖️",
		color: "#1890FF",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Bank Fees",
		icon: "🏦",
		color: "#FA541C",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Loan Payment",
		icon: "💳",
		color: "#722ED1",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Credit Card Payment",
		icon: "💳",
		color: "#F5222D",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Transfer & Withdrawal",
		icon: "💸",
		color: "#13C2C2",
		isSystemCategory: true,
		isActive: true,
	},
	{
		name: "Other",
		icon: "📌",
		color: "#8C8C8C",
		isSystemCategory: true,
		isActive: true,
	},
];

const seed = async () => {
	await prisma.category.deleteMany();
	await prisma.category.createMany({
		data: categories,
	});
};

seed();
